spring:
  datasource:
    url: jdbc:mysql://localhost:3306/article?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
