spring:
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
  datasource:
    url: jdbc:mysql://192.168.1.142:3306/article?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
aliyun:
  sourthFilePath: C:\Users\sunwukong\Desktop\oss_
  ossHead: https://video-pl.oss-cn-huhehaote.aliyuncs.com/
  parameter:
    - LTAICzLVPlryaIad,jLUlSxOaWqvNnIkh5aA7l3zPa8lZzY,mElJH70O6zjh7tbC # 最帅的我
    - LTAIdE6AWydq3Ibs,rlgvzy9EYb6MH9BNnRdZFTS3jo1MQn,odweG1CiXlO8l7a0 # 老范
    - LTAI4Fx4iwndSX3WSs7YAT77,FwZ1qNSktL2QxxF5yotBmTDSQULZvW,dYnOfxT9FxQVpQUz # end
    - LTAI4FjmPiDy39Q4qP9RHQcP,NxUyQRBOtCRtnNFbIj1NPMtW9t3WFO,2qbmKl2Zqmzfeow5 # 傲天
    - LTAI4FkAJGxMzg9c6VPQNAhb,eoDwkWAuKlysBW7L9YZ8v93EOW9APU,G5Ht4lVVZp2zrR9p # 晓峰
    - LTAI4FnPLH38uqifNkaxQA3V,IFe2whkcJvZsfE5StJDxPdCHq5d2lV,XBdje8VnRnCI2a1J # 钟远
    - LTAI4FurebiMJeDydy7Cj35x,Zn1FfQKimPJLfJK5s8LjmjYX6EOW4a,krYh2uvdNLFbCsL1 # 少鹏
    - LTAIaiQx67nvXNBX,BHFxkFOOn2eFY4TzixRFIaeGx5o5em,XUqeJmFEGGHw8hJ1 # 孝一
    - LTAI4FvkfqwuZEy15Km2thVc,WxhA1e9SObuvRJjSEkyGLr1sLvOFxu,iNnTjUQZZ9X7jEon # 唐培
    - LTAI4Fo1BJwmAyfeaxFpQz9A,fjAjyqgvZZexUxiWipZM57HC8CEWK7,DPpVkXdQmtrAnG9q # 张文秀
    - LTAI4FnfEP3RQnyctdhM4WXU,jOqPK9n03vhe2zoifONpLs9aA96xML,jMnYWJyp1ODzWo5G # 薛谨
    - LTAI4FpDg77XGHPNqZZgPBEH,lKYvXScULTa6oa5pHwFjvLCAwjwXbo,D1RiYxZVnML9ixQL # 周一
    - LTAI4FrBUugMwDyF9TDAtAzU,XwFJBNmoRyV2zhc6FxZ0lEOVAHqIWf,NcBffVOWAhY1wPOu # 朱婷婷
    - LTAI4FsjJ1svRsWfP1D7bRCQ,z5xuhNjyUIJOzlwbaoGMtUofQohld1,iTBm68oxxrvULcIu # 黄欣
    - LTAI4FjyfQ8DTpUdPxaoyaCw,a7qYfF0O3WJqLi0R6lnR4Cmn6DRxvL,oPPNvfcWc7In1sZ6 # 姜东序
  #  accessKeyId+","+accessKeySecret+","+appKey



